SUPABASE_URL = "https://ozruxykyvydwnyvlfyra.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cnV4eWt5dnlkd255dmxmeXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0OTY2MTYsImV4cCI6MjA4NDA3MjYxNn0.jRe116HetYoglDHI73C74as_Fp2LCQvAUYKDsAUIr3c"

ADMIN_PASSWORD = "Gestao@2026"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cnV4eWt5dnlkd255dmxmeXJhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODQ5NjYxNiwiZXhwIjoyMDg0MDcyNjE2fQ.iJd9nbazZ1PWfEC2Gb1b4quSsQ6j9bzLY8bx6We04cs"